#!/bin/bash
#
#  Copyright (c) 2006, 2014 SGI. All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

## pft-multirunX -- invoke runpft with varying args

# for plot annotations
PLATFORM=$(dmidecode -s system-product-name)
if [[ -n "$PLATFORM" ]];  then
	PLATFORM=$( echo "$PLATFORM" | awk '{print $1"-"$2$3;}')
else
	PLATFORM=Unknown
fi

# better way to determine nr_cpus?
nr_cpus=$(cat /proc/cpuinfo | grep  '^processor' | wc -l)
nr_nodes=$(ls -1d /sys/devices/system/node/node[0-9]* | wc -l)

# TESTING=true
TESTING=false
export NOEXEC=$TESTING VERBOSE=$TESTING

TIMESTAMP="$(date +%y%m%d-%H%M%S)"

# "runpft" will run pft_mpol for nr_threads = 1 .. nr_cpus,
# multiple times for each thread count for averaging, ...
RUNPFT="/usr/local/bin/runpft"

# use os revision for pft "tag"
osrev=$(uname -r)
#osrev=${osrev#2.6.}	# drop the 2.6.

# Memory Size -- if not set, calc from  GB_PER_TASK * nr_tasks)
#MEMSIZE="-m 4g"
MEMSIZE="-m 0"		# required to use GB_PER_TASK
GB_PER_TASK="-g 8"

# Number of Runs Per Thread count:
NRPT="-N 4"

# Affinitize -- bind to cpus
BIND="-af"

# Nodebind:  affinitize job to specified nodes
#NODEBIND=
NODEBIND="numactl --cpunodebind 1"

outprefix=pft_allnodes-$PLATFORM-$osrev-$TIMESTAMP

STOP_FILE=./pft_stop_file

{
	# pft_mpol build version/timestamp:
	pft_mpol -V
	echo "PLOTID pft_multirun-plotid"	# edit as needed
	echo "TITLE Single Node Scalability - ${GB_PER_TASK##* }/task"
	echo "SUBTITLE $PLATFORM $osrev"


	echo "LEGEND no additional patches "
	rm -f $STOP_FILE
	# anon mem, sys default mpol, touch to fault
	$NODEBIND $RUNPFT $NRPT $MEMSIZE $GB_PER_TASK $BIND "$osrev"
	## anon mem, explicit local mpol, touch to fault
	#$NODEBIND $RUNPFT $NRPT $MEMSIZE $GB_PER_TASK $BIND -p "$osrev"
	## shmem, sys default mpol, touch to fault
	#$NODEBIND $RUNPFT $NRPT $MEMSIZE $GB_PER_TASK $BIND -S "$osrev"
	## shmem, explicit local mpol, touch to fault
	#$NODEBIND $RUNPFT $NRPT $MEMSIZE $GB_PER_TASK $BIND -S -p "$osrev"
} > ${outprefix}.pft 2>&1
